# Generated by Django 3.2.5 on 2021-07-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpu_consulting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='title_picture',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
